import { User } from "@/lib/types/user";

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Carlos Ortega",
    email: "carlos.ortega@vadin.com",
    role: "Admin",
    department: "Controles",
    status: "active",
    createdAt: "2024-01-10T08:30:00Z",
  },
  {
    id: "u2",
    name: "Elena Guanche",
    email: "elena.g@vadin.com",
    role: "Editor",
    department: "A+B",
    status: "active",
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "u3",
    name: "Marcos Pérez",
    email: "marcos.p@vadin.com",
    role: "Editor",
    department: "Comercial",
    status: "inactive",
    createdAt: "2024-03-01T14:20:00Z",
  },
  {
    id: "u4",
    name: "Lucía Méndez",
    email: "lucia.m@vadin.com",
    role: "Espectador",
    department: "Economía",
    status: "active",
    createdAt: "2024-03-12T09:45:00Z",
  },
  {
    id: "u5",
    name: "Roberto Díaz",
    email: "roberto.d@vadin.com",
    role: "Espectador",
    department: "RRHH",
    status: "active",
    createdAt: "2024-04-05T11:15:00Z",
  },
  {
    id: "u6",
    name: "Ana Belén",
    email: "ana.b@vadin.com",
    role: "Editor",
    department: "Seguridad",
    status: "active",
    createdAt: "2024-04-20T16:00:00Z",
  },
  {
    id: "u7",
    name: "Sergio Ramos",
    email: "sergio.r@vadin.com",
    role: "Espectador",
    department: "AtCliente",
    status: "inactive",
    createdAt: "2024-05-02T13:10:00Z",
  },
];
