/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicProjectProjectIdRouteImport } from './routes/public-project.$projectId'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAuthenticatedOnboardingRouteImport } from './routes/_layout/_authenticated/onboarding'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAuthenticatedDashboardIndexRouteImport } from './routes/_layout/_authenticated/dashboard/index'
import { Route as LayoutAuthenticatedDashboardSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/settings'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId'
import { Route as LayoutAuthenticatedDashboardSettingsAppearanceRouteImport } from './routes/_layout/_authenticated/dashboard/settings/appearance'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/settings'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/phone-board'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/analytics'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/settings'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/new'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/$id'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/new'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_'

const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProjectProjectIdRoute = PublicProjectProjectIdRouteImport.update({
  id: '/public-project/$projectId',
  path: '/public-project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedOnboardingRoute =
  LayoutAuthenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardIndexRoute =
  LayoutAuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsRoute =
  LayoutAuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAppearanceRoute =
  LayoutAuthenticatedDashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRouteImport.update({
    id: '/phone-board',
    path: '/phone-board',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteImport.update({
    id: '/event-rooms',
    path: '/event-rooms',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRouteImport.update(
    {
      id: '/project/$projectId/',
      path: '/project/$projectId/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRouteImport.update(
    {
      id: '/manage/',
      path: '/manage/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRouteImport.update(
    {
      id: '/project/$projectId/settings',
      path: '/project/$projectId/settings',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport.update(
    {
      id: '/project/$projectId/board',
      path: '/project/$projectId/board',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport.update(
    {
      id: '/project/$projectId/backlog',
      path: '/project/$projectId/backlog',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRouteImport.update(
    {
      id: '/reservations/new',
      path: '/reservations/new',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRouteImport.update(
    {
      id: '/reservations/$id',
      path: '/reservations/$id',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRouteImport.update(
    {
      id: '/manage/new',
      path: '/manage/new',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRouteImport.update(
    {
      id: '/manage/$roomId',
      path: '/manage/$roomId',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport.update(
    {
      id: '/project/$projectId/task/$taskId_',
      path: '/project/$projectId/task/$taskId',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/appearance': typeof LayoutAuthenticatedDashboardSettingsAppearanceRoute
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/dashboard/workspace/$workspaceId/analytics': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRoute
  '/dashboard/workspace/$workspaceId/event-rooms': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteWithChildren
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/phone-board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId/settings': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRoute
  '/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/workspace/$workspaceId/event-rooms/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRoute
  '/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRoute
  '/dashboard/workspace/$workspaceId/event-rooms/manage/new': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRoute
  '/dashboard/workspace/$workspaceId/event-rooms/reservations/$id': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRoute
  '/dashboard/workspace/$workspaceId/event-rooms/reservations/new': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/settings': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute
  '/dashboard/workspace/$workspaceId/event-rooms/manage': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRoute
  '/dashboard/workspace/$workspaceId/project/$projectId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/appearance': typeof LayoutAuthenticatedDashboardSettingsAppearanceRoute
  '/dashboard/workspace/$workspaceId/analytics': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRoute
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/phone-board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId/settings': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRoute
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/workspace/$workspaceId/event-rooms': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRoute
  '/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRoute
  '/dashboard/workspace/$workspaceId/event-rooms/manage/new': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRoute
  '/dashboard/workspace/$workspaceId/event-rooms/reservations/$id': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRoute
  '/dashboard/workspace/$workspaceId/event-rooms/reservations/new': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/settings': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute
  '/dashboard/workspace/$workspaceId/event-rooms/manage': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRoute
  '/dashboard/workspace/$workspaceId/project/$projectId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/_layout/_authenticated/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/_layout/_authenticated/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/_layout/_authenticated/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/_layout/_authenticated/dashboard/settings/appearance': typeof LayoutAuthenticatedDashboardSettingsAppearanceRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/analytics': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/phone-board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/settings': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/new': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/$id': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/new': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/settings': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/test-error'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/public-project/$projectId'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/appearance'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/workspace/$workspaceId/analytics'
    | '/dashboard/workspace/$workspaceId/event-rooms'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/phone-board'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId/settings'
    | '/dashboard/workspace/$workspaceId/'
    | '/dashboard/workspace/$workspaceId/event-rooms/'
    | '/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId'
    | '/dashboard/workspace/$workspaceId/event-rooms/manage/new'
    | '/dashboard/workspace/$workspaceId/event-rooms/reservations/$id'
    | '/dashboard/workspace/$workspaceId/event-rooms/reservations/new'
    | '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/project/$projectId/settings'
    | '/dashboard/workspace/$workspaceId/event-rooms/manage'
    | '/dashboard/workspace/$workspaceId/project/$projectId'
    | '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/test-error'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/public-project/$projectId'
    | '/onboarding'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/settings/appearance'
    | '/dashboard/workspace/$workspaceId/analytics'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/phone-board'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId/settings'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/workspace/$workspaceId/event-rooms'
    | '/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId'
    | '/dashboard/workspace/$workspaceId/event-rooms/manage/new'
    | '/dashboard/workspace/$workspaceId/event-rooms/reservations/$id'
    | '/dashboard/workspace/$workspaceId/event-rooms/reservations/new'
    | '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/project/$projectId/settings'
    | '/dashboard/workspace/$workspaceId/event-rooms/manage'
    | '/dashboard/workspace/$workspaceId/project/$projectId'
    | '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/test-error'
    | '/_layout/_authenticated'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/public-project/$projectId'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/onboarding'
    | '/_layout/_authenticated/dashboard/settings'
    | '/_layout/_authenticated/dashboard/'
    | '/_layout/_authenticated/dashboard/settings/appearance'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/analytics'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/phone-board'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/settings'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/new'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/$id'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/new'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/settings'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  TestErrorRoute: typeof TestErrorRoute
  PublicProjectProjectIdRoute: typeof PublicProjectProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-project/$projectId': {
      id: '/public-project/$projectId'
      path: '/public-project/$projectId'
      fullPath: '/public-project/$projectId'
      preLoaderRoute: typeof PublicProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/onboarding': {
      id: '/_layout/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof LayoutAuthenticatedOnboardingRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard/': {
      id: '/_layout/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings': {
      id: '/_layout/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/dashboard/workspace/$workspaceId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings/appearance': {
      id: '/_layout/_authenticated/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAppearanceRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
      path: '/'
      fullPath: '/dashboard/workspace/$workspaceId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/settings': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/dashboard/workspace/$workspaceId/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
      path: '/search'
      fullPath: '/dashboard/workspace/$workspaceId/search'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/phone-board': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/phone-board'
      path: '/phone-board'
      fullPath: '/dashboard/workspace/$workspaceId/phone-board'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
      path: '/members'
      fullPath: '/dashboard/workspace/$workspaceId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms'
      path: '/event-rooms'
      fullPath: '/dashboard/workspace/$workspaceId/event-rooms'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/analytics': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/analytics'
      path: '/analytics'
      fullPath: '/dashboard/workspace/$workspaceId/analytics'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/'
      path: '/'
      fullPath: '/dashboard/workspace/$workspaceId/event-rooms/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/'
      path: '/manage'
      fullPath: '/dashboard/workspace/$workspaceId/event-rooms/manage'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/settings': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/settings'
      path: '/project/$projectId/settings'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board'
      path: '/project/$projectId/board'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/board'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog'
      path: '/project/$projectId/backlog'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/new': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/new'
      path: '/reservations/new'
      fullPath: '/dashboard/workspace/$workspaceId/event-rooms/reservations/new'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/$id': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/dashboard/workspace/$workspaceId/event-rooms/reservations/$id'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/new': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/new'
      path: '/manage/new'
      fullPath: '/dashboard/workspace/$workspaceId/event-rooms/manage/new'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId'
      path: '/manage/$roomId'
      fullPath: '/dashboard/workspace/$workspaceId/event-rooms/manage/$roomId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_'
      path: '/project/$projectId/task/$taskId'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
  }
}

interface LayoutAuthenticatedDashboardSettingsRouteChildren {
  LayoutAuthenticatedDashboardSettingsAppearanceRoute: typeof LayoutAuthenticatedDashboardSettingsAppearanceRoute
}

const LayoutAuthenticatedDashboardSettingsRouteChildren: LayoutAuthenticatedDashboardSettingsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAppearanceRoute:
      LayoutAuthenticatedDashboardSettingsAppearanceRoute,
  }

const LayoutAuthenticatedDashboardSettingsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsRouteChildren,
  )

interface LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteChildren {
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRoute
}

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteChildren: LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteChildren =
  {
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageRoomIdRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageNewRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsIdRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsReservationsNewRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsManageIndexRoute,
  }

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteWithChildren =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute._addFileChildren(
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteChildren,
  )

interface LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren {
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteWithChildren
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren: LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren =
  {
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAnalyticsRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdEventRoomsRouteWithChildren,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdPhoneBoardRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSettingsRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute,
  }

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute._addFileChildren(
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteChildren {
  LayoutAuthenticatedDashboardSettingsRoute: typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  LayoutAuthenticatedDashboardIndexRoute: typeof LayoutAuthenticatedDashboardIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
}

const LayoutAuthenticatedDashboardRouteChildren: LayoutAuthenticatedDashboardRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsRoute:
      LayoutAuthenticatedDashboardSettingsRouteWithChildren,
    LayoutAuthenticatedDashboardIndexRoute:
      LayoutAuthenticatedDashboardIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren,
  }

const LayoutAuthenticatedDashboardRouteWithChildren =
  LayoutAuthenticatedDashboardRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRouteWithChildren
  LayoutAuthenticatedOnboardingRoute: typeof LayoutAuthenticatedOnboardingRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute:
    LayoutAuthenticatedDashboardRouteWithChildren,
  LayoutAuthenticatedOnboardingRoute: LayoutAuthenticatedOnboardingRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  TestErrorRoute: TestErrorRoute,
  PublicProjectProjectIdRoute: PublicProjectProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
